### ISSUE TITLE
Jsonxx's Unit Testing Mode terminates the mod loader.

### ISSUE THREAD

**Issue by FlavorfulGecko5** [PowerBall253/EternalModLoaderCpp#7]
If the mod loader encounters a badly malformed JSON, it will forcibly terminate mid-execution instead of allowing an exception to propagate.

Screenshot of example output (provided by Alby): ![image](https://github.com/PowerBall253/EternalModLoaderCpp/assets/4349074/76ddb929-1e61-4c23-9a5a-50e2cfc77db4)

Using the error message we can track the issue down to jsonxx's assert function, probably intended for use in Unit Testing.

Code snippet from `vendor/jsonxx/jsonxx.cc`
![image](https://github.com/PowerBall253/EternalModLoaderCpp/assets/4349074/dff42dae-1286-416d-9a5b-929f3a364b53)

Unit Testing should be disabled by changing an enum's value in `vendor/jsonxx/jsonxx.h` 
![image](https://github.com/PowerBall253/EternalModLoaderCpp/assets/4349074/a476fb12-591a-4e71-b32d-67ffb01fe97b)

Disclaimer: I am not on a Linux environment. Someone who is should quickly verify that JSON exceptions are being properly caught after implementing this fix.

**Comment by PowerBall253** [comment]
Thanks for opening the issue! Do you happen to have any mod examples for testing the change?

**Comment by PowerBall253** [comment]
Test build for this change is available at <https://github.com/PowerBall253/EternalModLoaderCpp/suites/15241577456/artifacts/870991645>
